## åˆ©ç”¨GitHub Actionsæ¯å¤©å®šæ—¶ç»™ç™¾åº¦æ¨é€é“¾æ¥ï¼Œæé«˜æ”¶å½•ç‡ ##

name: baiduPush

# ä¸¤ç§è§¦å‘æ–¹å¼ï¼šä¸€ã€pushä»£ç ï¼ŒäºŒã€æ¯å¤©å›½é™…æ ‡å‡†æ—¶é—´23ç‚¹ï¼ˆåŒ—äº¬æ—¶é—´+8å³æ—©ä¸Š7ç‚¹ï¼‰è¿è¡Œ
on:
  push:
  schedule:
    - cron: '0 23 * * *' # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
  workflow_dispatch:

# on:
#   schedule:
#     - cron: '*/5 * * * *' # æ¯5åˆ†é’Ÿä¸€æ¬¡ï¼Œæµ‹è¯•ç”¨

jobs:
  bot:
    runs-on: ubuntu-latest # è¿è¡Œç¯å¢ƒä¸ºæœ€æ–°ç‰ˆçš„Ubuntu
    steps:
      # æ‹‰å–ä»£ç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      # å…è®¸è„šæœ¬
      - name: Run baiduPush ğŸš€
        run: yarn install && yarn baiduPush
