# name å¯ä»¥è‡ªå®šä¹‰
name: Build Vitepress

# è§¦å‘æ¡ä»¶ï¼šåœ¨ push åˆ° main/master åˆ†æ”¯åï¼Œæ–°çš„ Github é¡¹ç›® åº”è¯¥éƒ½æ˜¯ mainï¼Œè€Œä¹‹å‰çš„é¡¹ç›®ä¸€èˆ¬éƒ½æ˜¯ master
on:
  push:
    branches:
      - master
  workflow_dispatch:

# ä»»åŠ¡
jobs:
  build-and-deploy:
    # æœåŠ¡å™¨ç¯å¢ƒï¼šæœ€æ–°ç‰ˆ Ubuntu
    runs-on: ubuntu-latest
    steps:
      # æ‹‰å–ä»£ç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup-node ğŸ’ª
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      # ç”Ÿæˆé™æ€æ–‡ä»¶
      - name: Install and Build ğŸ”§
        run: yarn install --frozen-lockfile && yarn build

      # éƒ¨ç½²åˆ° GitHub Pages
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_KEY }} # ä¹Ÿå°±æ˜¯æˆ‘ä»¬åˆšæ‰ç”Ÿæˆçš„ secret
          BRANCH: gh-pages # éƒ¨ç½²åˆ° gh-pages åˆ†æ”¯ï¼Œå› ä¸º main åˆ†æ”¯å­˜æ”¾çš„ä¸€èˆ¬æ˜¯æºç ï¼Œè€Œ gh-pages åˆ†æ”¯åˆ™ç”¨æ¥å­˜æ”¾ç”Ÿæˆçš„é™æ€æ–‡ä»¶
          FOLDER: docs/.vitepress/dist # vuepress ç”Ÿæˆçš„é™æ€æ–‡ä»¶å­˜æ”¾çš„åœ°æ–¹

      - name: sync-gitee-mirror
        run: |
          git add .
          git commit '123'
          remote_repo="https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_PASSWORD }}@gitee.com/pmun/sync-blog-pages.git"
          git remote add gitee "${remote_repo}"
          git show-ref # useful for debugging
          git branch --verbose
          # publish all
          git push --all --force gitee
          git push --tags --force gitee
        shell: bash
